### ISSUE TITLE
[ Question ] Neutralinojs supports web as a target (or not)?

### ISSUE THREAD

**Issue by shalithasuranga** [Elanis/web-to-desktop-framework-comparison#10]
If we run the Neutralinojs in `cloud` mode and bind to a domain, anyone can access it as a web application. But all the native functionalities won't run purely inside the browser. So maybe we could add a small hint about this scenario into your comparison. Maybe "Partial" instead of the red icon in the "Operating System" section?

Just an idea. you can check more about `cloud` mode here: https://neutralino.js.org/docs/developer-environment/modes#cloud

Thanks for creating an awesome comparison!

**Comment by Elanis** [comment]
Hello !

Thank you for your comment :) I'll look at this feature and how to integrate it into my comparison. It could be nice to mention that indeed. I'll update this issue when done.

Nice work with Neutralino btw

**Comment by shalithasuranga** [comment]
Thanks, @Elanis  for the quick response.

**Comment by Elanis** [comment]
This detail was added to the README, Thanks :) 

If you feel any other important information is missing in the repo, do not hesitate to comment here or open another issue.
