### ISSUE TITLE
Frameless TAURI available

### ISSUE THREAD

**Issue by nothingismagick** [Elanis/web-to-desktop-framework-comparison#12]
Frameless Tauri is available since the beta

**Comment by Elanis** [comment]
Hello, could you give me a link to the documentation ? I seeked for it during the example update, but I didn't found information about a frameless mode.

I'll then update examples.

Thanks :)

**Comment by nothingismagick** [comment]
https://tauri.studio/en/docs/api/config/#tauri.windows

**Comment by nothingismagick** [comment]
https://tauri.studio/en/docs/usage/guides/visual/window-customization

**Comment by Elanis** [comment]
Oh thanks, I read this page but didn't see the config I was looking for 😄 I will update that !

**Comment by Elanis** [comment]
Frameless example was added, thanks !
