### ISSUE TITLE
Tauri is no longer using MSHTML on windows

### ISSUE THREAD

**Issue by nothingismagick** [Elanis/web-to-desktop-framework-comparison#13]
> Cocoa/WebKit on macOS, gtk-webkit2 on Linux and MSHTML (IE10/11) or Webkit via Edge on Windows

Please see https://github.com/tauri-apps/wry

**Comment by Elanis** [comment]
Hello, thanks, I fixed this information in the table :) Are the informations now valid ?

**Comment by nothingismagick** [comment]
Great

**Comment by Elanis** [comment]
Perfect, thanks
