### ISSUE TITLE
Consider adding minification build flags

### ISSUE THREAD

**Issue by nothingismagick** [Elanis/web-to-desktop-framework-comparison#14]
Your build size is still too large. Rust offers a number of opportunities to make binaries smaller. Please see this page:

https://tauri.studio/en/docs/usage/guides/bundler/anti-bloat

And at least put this at the end of your Cargo.toml:

```
[profile.release]
panic = "abort"
codegen-units = 1
lto = true
incremental = false
opt-level = "s"
```

**Comment by Elanis** [comment]
I added your instructions to both Cargo.toml. I don't know alot about Rust, will test some more changes later, but it's a good start :)

Keeping this issue open to remind myself
