### ISSUE TITLE
Find an alternative to nwjs-builder-phoenix

### ISSUE THREAD

**Issue by Elanis** [Elanis/web-to-desktop-framework-comparison#16]

**Comment by Elanis** [comment]
Waiting for https://github.com/nwjs/nw.js/issues/7693

**Comment by Elanis** [comment]
![image](https://github.com/Elanis/web-to-desktop-framework-comparison/assets/7013446/990f677d-a69d-482c-8587-63a5fec013c0)

I really should take some time to migrate this because dependabot alerts are accumulating about nwjs-builder-phoenix 😅

**Comment by paulocoghi** [comment]
Maybe [nwutils/nwjs-packager](https://github.com/nwutils/nwjs-packager)? It's actively maintained

**Comment by Elanis** [comment]
Ahah, don't worry.

I indeed won't use nwjs-packager, because of its README header. It looks like it won't evolve a lot more anymore (except if one decides to contributes massively)
