### ISSUE TITLE
Add maui+blazor and kotlin in list 

### ISSUE THREAD

**Issue by skimhugo** [Elanis/web-to-desktop-framework-comparison#172]
Maui+blazor can use js/ts to build the forentend part.

**Comment by Elanis** [comment]
Hi,

Indeed, I'd like to talk about MAUI/Blazor too.

Kotlin is a bit large, I guess it should have a lot of possible techs. (And I don't know at all Java environments tbh)

**Comment by skimhugo** [comment]
I will do some work on maui+blazor+vue/react, I think it is the best solution ever in multi-platform for web tech.

Blazor is a wasm env, it can be the bridge in c# and js. I'm still not sure about the whole mechanism. In tauri app, some case use WebSocket does the interpo.

**Comment by Elanis** [comment]
Yup, no problem, I only need you to create a seperate example from existing MAUI one, so we can benchmark both solutions :)
