### ISSUE TITLE
Add Revery to the list

### ISSUE THREAD

**Issue by brainwo** [Elanis/web-to-desktop-framework-comparison#181]
[Revery](https://github.com/revery-ui/revery) is a work-in-progress cross-platform UI toolkit that doesn't use native GUI library (similar to Flutter). It uses Electron under-the-hood bundled with native React/Redux-like libraries and claims to be more performant in term of CPU+RAM usages than using Electron directly.

**Comment by Elanis** [comment]
Nice ! thanks for the idea !

**Comment by Elanis** [comment]
The project seems kinda dead
