### ISSUE TITLE
Add Wails to the list

### ISSUE THREAD

**Issue by jellydn** [Elanis/web-to-desktop-framework-comparison#266]
# What
- Consider to add Wails to the list
https://wails.io/
Build beautiful cross-platform applications using Go

# How
- Create similar app like Tauri

# Why

- Wails is a project that enables you to write desktop apps using Go and web technologies.

- Consider it a lightweight and fast Electron alternative for Go. You can easily build applications with the flexibility and power of Go, combined with a rich, modern frontend.

**Comment by Elanis** [comment]
Hi ! 

Thanks for the proposition but it was already proposed in #46 :)

I'm closing this issue as duplicate.

**Comment by jellydn** [comment]
Thanks :) Sorry, I didn’t see that open issue.

**Comment by Elanis** [comment]
No problem :)
