### ISSUE TITLE
Add a table to show support of known front framework

### ISSUE THREAD

**Issue by Elanis** [Elanis/web-to-desktop-framework-comparison#301]
Show if (not) supported and if available template for:
- Angular
- React
- Vue
- Svelte
- etc.

**Comment by joshwambere** [comment]
@Elanis can i have this?

**Comment by Elanis** [comment]
Yup, no problem, you can open a PR with this if you wish :)

**Comment by gpsakthivel** [comment]
Hi @Elanis, Is this issue done or can i take a look into it?

**Comment by Elanis** [comment]
Hi @gpsakthivel, this isn't done nope, you can look into it :)

**Comment by gpsakthivel** [comment]
Wow @Elanis . Thanks for the swift response.

A small clarification: 
1. How do you want me to proceed with the request?
2. Can I add details for the Angular, React, Vue, Svelte similar to the major characteristics implementation?

**Comment by Elanis** [comment]
No problem :)

I think you can add a table after Operating system support using the same layout as both previous tables.

Also, be sure, to add links to sources (e.g. official documentation) if you can find some, so people can look into it while scrolling the repo :)

I listed 4 frameworks/libs but if you feel you need to add more relevant lines to the result, you can too. E.g. Vite Support or other frameworks.

Hit me up here if you need more informations

**Comment by gpsakthivel** [comment]
@Elanis - Can you please review the below PR?
https://github.com/Elanis/web-to-desktop-framework-comparison/pull/580

**Comment by gpsakthivel** [comment]
Note:

- Use **ALT + Z** in the VS code editor to view the changes.
- A lot of space will be available because to order the table i did that changes.

FYI - @Elanis
