### ISSUE TITLE
Add gluonjs to the list

### ISSUE THREAD

**Issue by Elanis** [Elanis/web-to-desktop-framework-comparison#342]
https://github.com/gluon-framework/gluon

**Comment by paulocoghi** [comment]
Seems promising and I can't wait to see its memory usage. Already experimenting with it.

**Comment by paulocoghi** [comment]
But I still believe that no one on the list, even Gluon, would be able to beat Sciter on memory usage. No one, by far.

**Comment by jodaka** [comment]
Their website is offline and github repo is in read-only. It looks like this issue can be closed 😅

**Comment by Elanis** [comment]
Uh oh, indeed 😅
