### ISSUE TITLE
Add Build Time Benchmark?

### ISSUE THREAD

**Issue by LazyGeniusMan** [Elanis/web-to-desktop-framework-comparison#36]
Hi, nice comparison. Is it possible and relevant to add build time?

Thanks.

**Comment by Elanis** [comment]
Hi !

Thanks, indeed that could be an idea :) I'm currently thinking about doing something to automate benchmark creation (because I wanna do multiple projects in this repo to try everything out). So I'm gonna add this idea to my list :)

Keeping this issue open, so I don't forget about it

**Comment by LazyGeniusMan** [comment]
> I'm currently thinking about doing something to automate benchmark creation

Not really familiar with this but maybe you can use github action ?, maybe it's viable to get build size, memory consumption, start time, and build time.

**Comment by Elanis** [comment]
Yup, will probably use some CI like Github Actions, but I still need some scripts to measure data :)

**Comment by Elanis** [comment]
WIP, already done for electron/nw.js, am currently working on upgrading everything, will add build size/time with these PR
