### ISSUE TITLE
How to run Neutralinojs benchmark source

### ISSUE THREAD

**Issue by oHaiyang** [Elanis/web-to-desktop-framework-comparison#40]
Hi, I have tried running neutralinojs benchmark on Linux with different neu CLI versions, the CLI complaints about the bin file not existing.

here are screen shots:

tried with latest neu-cli:

<img width="666" alt="image" src="https://user-images.githubusercontent.com/2813250/153134120-16f877cb-2850-45e5-a847-26c1b17f8670.png">

tried with older version of neu-cli:
<img width="825" alt="image" src="https://user-images.githubusercontent.com/2813250/153134365-04ed63ad-1819-46fe-87ff-0dce4c9a1717.png">

could you post your way to run or build the benchmark source?

**Comment by Elanis** [comment]
Hi !

Sorry for the time, didn't have time to look at your problem earlier.

I wasn't able to run my old version on Windows as well (for another reason) to test and help you, so I re-created both neutralino benchmark apps.

It now works on both Windows and WSLg (embed Debian 11) systems without any change to the benchmark results.

Does it fix your problem ?

**Comment by oHaiyang** [comment]
Sorry for the late feedback： after syncing with the changes I got the benchmark run. Thansk!

by the way, for anyone who may encounter the same question:

```bash
# clone the repo then cd to neutralinojs directory
npx @neutralinojs/neu@5 update
npx @neutralinojs/neu@5 run
```

**Comment by Elanis** [comment]
No problem ! Amazing :)
