### ISSUE TITLE
Addition of wails to the comparison list

### ISSUE THREAD

**Issue by kishaningithub** [Elanis/web-to-desktop-framework-comparison#46]
It would be great if you can add [wails](https://github.com/wailsapp/wails) to your comparison list :-)

https://github.com/wailsapp/wails

From what is see it is architecturally similar to tauri and the api layer is written in golang

It would be great to have a detailed comparison 

Thanks in advance :-)

**Comment by Elanis** [comment]
Hi ! 
Indeed, this could be a nice candidate for this comparison.
I never used Go, but following documentation, it shouldn't be too hard :smile:

Keeping this issue open until I have some time to do it :)

Thanks for your proposition !
