### ISSUE TITLE
Neutralinojs memory consumption

### ISSUE THREAD

**Issue by Arm1** [Elanis/web-to-desktop-framework-comparison#58]
Even if I am a huge fan of your project, I don't think that neutralino can take only 5 Mo of memory. The Edge webview uses at least 60 Mo. Maybe I'm wrong ...
![image](https://user-images.githubusercontent.com/11499410/169694841-b18b841b-d918-4429-858a-6e6771c96a0a.png)

**Comment by Elanis** [comment]
Hi ! Will look into that asap ;)

**Comment by Elanis** [comment]
Yup, I looked into this with #61 which will auto-benchmark everything, and neutralino was indeed too low, I might have made an error when manually benchmarking 😄 

It'll be fixed with this PR being merged into main. Thanks !
