### ISSUE TITLE
mermaid .js

### ISSUE THREAD

**Issue by lucasnuic** [Elanis/web-to-desktop-framework-comparison#712]
add mermaid as report here?

#### stars and forks
```mermaid
gantt
    title Github stars
    dateFormat  X
    axisFormat %s

    section Electron
    111900  : 0, 111900   
    section NW.JS
    40100 : 0, 40100 
    section Tauri
    77100 : 0, 77100
    section NodeGUI
    8700  : 0, 8700
    section Neutralino
    7200  : 0, 7200
    section Wails
    22100 : 0, 22100
    section Flutter
    161700: 0, 161700
    section .Net MAUI
    21500: 0, 21500

```

**Comment by Elanis** [comment]
Hm, I don't really like this format, if there's an histogram shape, maybe it would be better ? 
Plus it would probably be on a separate .md file I think, because it would take too much space on the main README.

But it's definitely worth trying going in that direction!

**Comment by Elanis** [comment]
The histogram could work like that yes!

I also saw this when browsing mermaid formats
```mermaid
gantt
    title Github stars
    dateFormat  X
    axisFormat %s

    section Electron
    111900  : 0, 111900   
    section NW.JS
    40100 : 0, 40100 
    section Tauri
    77100 : 0, 77100
    section NodeGUI
    8700  : 0, 8700
    section Neutralino
    7200  : 0, 7200
    section Wails
    22100 : 0, 22100
    section Flutter
    161700: 0, 161700
    section .Net MAUI
    21500: 0, 21500
```

But I'm scared the font would be too small ?

**Comment by Elanis** [comment]
I reopen because it wasn't done :)
I was looking into ways to alter font size (it can be done with mermaid but not sure if mermaid on github can), or other shapes

**Comment by Elanis** [comment]
I just created a script to auto-generate GRAPHS.md using the data we get for forks/stars, we'll see in the future if the format has to evolve or anything :)

**Comment by Elanis** [comment]
Thank you for your idea :)
